sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

#env:
#  global:
#    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  # Codecov
#  - bash <(curl -s https://codecov.io/bash)

  # Docker Hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=aydarik/amfibot
  - docker build -t $CONFIG:$TAG ./telegram-bot-springboot
#  - docker tag $CONFIG:$TAG $CONFIG:$COMMIT
  - docker push $CONFIG