package ru.gumerbaev.amfibot.database.entities;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;

@Entity
@Data
public class Query {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@ManyToOne
	private User user;

	private String message;

	private Date date;

	public void setId(long id) {
		// The id should not be set by clients, there this method is not
		// generated by lombok
	}
}
