package ru.gumerbaev.amfibot.database.entities;

import lombok.Data;

import javax.persistence.*;
import java.util.List;

@Data
@Entity
public class User {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	private long telegramId;
	private boolean is_bot;
	private String first_name;
	private String last_name;
	private String username;
	private String languageCode;

	@OneToMany
	private List<Query> queries;

	public void setId(long id) {
		// The id should not be set by clients, there this method is not
		// generated by lombok
	}
}
